# Prebuilt-artifact packaging: an el9 RPM plus a relocatable tarball,
# generated by CPack from the existing install rules (plugin .so, ucache CLI,
# user docs). The canonical build recipe is scripts/package-el9.sh — packages
# MUST be built with the host toolchain (system gcc), never an LCG shell, so
# the binaries' libstdc++/glibc requirements are stock-EL9.
#
# Runtime dependencies are the auto-generated soname Requires (liblzma.so.5,
# libzstd.so.1, libz.so.1, and glibc/libstdc++ versions) with ONE exception:
# the XRootD client library. The plugin never needs an XRootD installed from a
# package — it runs inside a process that has already loaded its client
# (/usr/bin/xrdcp, or a ROOT from CVMFS, conda or anywhere else), and a library
# whose name is already loaded is taken from the process, not the disk. A
# requirement on libXrdCl.so.3 would install an XRootD nobody uses on every
# machine that gets its XRootD from CVMFS, and one on libXrdCl.so.6 (the second
# build) would stop the package installing wherever XRootD 6 is absent.
# ucache-netbench links the client itself and runs where one is available.

# The installed set must be CLOSED under the pointers it contains: a doc that
# tells the reader to see another doc, which the package does not carry, is a
# dead end on exactly the machine where they cannot go and fetch it. Closure is
# TRANSITIVE and that is the whole reason to gate it rather than eyeball it —
# both guides point at BENCH.md, which points at STATS.md, which points at
# FORMAT.md. The packaging gate computes the closure and refuses to build a
# package that breaks it (scripts/package-el9.sh).
install(FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/USER_GUIDE.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/CACHE_MANAGEMENT.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/TROUBLESHOOTING.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/BENCH.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/PUBLISH.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/STATS.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/FORMAT.md
  ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE
  DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/doc/xrd-ucache)

# The recommended configuration, to COPY into a user's own
# ~/.xrootd/client.plugins.d/ (uCache is per user: nothing the package installs
# switches it on for anyone). Filled in with the plugin's path as the RPM
# installs it -- CPack's RPM prefix is /usr -- and a placeholder cache
# directory; `ucache setup` writes the same text with this install's own path.
# scripts/package-el9.sh checks, on a staged install laid out as the RPM, that
# the library this file names is there.
file(READ "${PROJECT_SOURCE_DIR}/share/ucache.conf.in" _ucache_conf)
string(REPLACE "{{URL}}" "*" _ucache_conf "${_ucache_conf}")
string(REPLACE "{{LIB}}" "/usr/${CMAKE_INSTALL_LIBDIR}/libXrdClUCache.so" _ucache_conf "${_ucache_conf}")
string(REPLACE "{{DIR}}" "/path/on/a/local/disk/ucache" _ucache_conf "${_ucache_conf}")
file(WRITE "${CMAKE_BINARY_DIR}/share/ucache.conf" "${_ucache_conf}")
install(FILES "${CMAKE_BINARY_DIR}/share/ucache.conf"
        DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/xrd-ucache)
# A ROOT macro that reads the same data twice and reports the difference: the
# README's first look at uCache working (`root -l -b -q .../ucache_try.C`).
install(FILES "${PROJECT_SOURCE_DIR}/share/ucache_try.C"
        DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/xrd-ucache)

set(CPACK_PACKAGE_NAME "xrd-ucache")
set(CPACK_PACKAGE_VENDOR "xrd-ucache")
set(CPACK_PACKAGE_CONTACT "Dmytro Kovalskyi <dmytro@cern.ch>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Transparent per-user read cache for remote ROOT/XRootD data")
# Tarball name (the RPM overrides its own below): unpacks into a single
# xrd-ucache-<version>-el9-x86_64/ prefix — extract with --strip-components=1.
# On macOS only the tarball is made, named for the architecture it holds.
if(APPLE)
  set(CPACK_PACKAGE_FILE_NAME
      "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-macos-${CMAKE_SYSTEM_PROCESSOR}")
  set(CPACK_GENERATOR "TGZ")
else()
  set(CPACK_PACKAGE_FILE_NAME
      "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-el9-x86_64")
  set(CPACK_GENERATOR "RPM;TGZ")
endif()
set(CPACK_STRIP_FILES ON)

set(CPACK_RPM_PACKAGE_LICENSE "MIT")         # copyright (c) MIT, LICENSE at repo root
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_RELEASE_DIST ON)       # -> 1.el9
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)         # -> xrd-ucache-<v>-1.el9.x86_64.rpm
set(CPACK_RPM_PACKAGE_DESCRIPTION
    "An XrdCl client plugin and CLI that cache the pages your jobs read from \
root:// URLs on local disk, so repeat passes over the same data are served \
locally. Fail-open by construction: any cache problem degrades to a normal \
uncached read. Activation is per-user and needs no administrator: run \
`ucache setup` once. The plugin is built twice, libXrdClUCache-5.so for \
XRootD 5.6+ clients and libXrdClUCache-6.so for XRootD 6, and a conf naming \
libXrdClUCache.so makes each client load its own. Works with the system \
client and with CMSSW, LCG/CVMFS and other ROOT builds; no XRootD package is \
required.")

# Lines added to the generated spec. The first drops the XRootD client library
# from the requirements (see the top of this file); the second works around
# hosts without /sbin/ldconfig, which rpm's brp-ldconfig step calls by that
# path and which is a no-op for this package anyway.
set(CPACK_RPM_SPEC_MORE_DEFINE "%global __requires_exclude ^libXrdCl[.]so")
if(NOT EXISTS /sbin/ldconfig)
  string(APPEND CPACK_RPM_SPEC_MORE_DEFINE "\n%define __brp_ldconfig %{nil}")
endif()

include(CPack)
