# Prebuilt-artifact packaging: an el9 RPM plus a relocatable tarball,
# generated by CPack from the existing install rules (plugin .so, ucache CLI,
# user docs). The canonical build recipe is scripts/package-el9.sh — packages
# MUST be built with the host toolchain (system gcc), never an LCG shell, so
# the binaries' libstdc++/glibc requirements are stock-EL9.
#
# Runtime dependencies are the auto-generated soname Requires (libXrdCl.so.3,
# liblzma.so.5, libzstd.so.1, libz.so.1) — any XRootD 5.x client install
# satisfies them; on EL9 that is EPEL's xrootd-client-libs.

install(FILES
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/USER_GUIDE.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/CACHE_MANAGEMENT.md
  ${CMAKE_CURRENT_SOURCE_DIR}/docs/TROUBLESHOOTING.md
  ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE
  DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/doc/xrd-ucache)

set(CPACK_PACKAGE_NAME "xrd-ucache")
set(CPACK_PACKAGE_VENDOR "xrd-ucache")
set(CPACK_PACKAGE_CONTACT "Dmytro Kovalskyi <dmytro@cern.ch>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "Transparent per-user read cache for remote ROOT/XRootD data")
# Tarball name (the RPM overrides its own below): unpacks into a single
# xrd-ucache-<version>-el9-x86_64/ prefix — extract with --strip-components=1.
set(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-el9-x86_64")
set(CPACK_GENERATOR "RPM;TGZ")
set(CPACK_STRIP_FILES ON)

set(CPACK_RPM_PACKAGE_LICENSE "MIT")         # copyright (c) MIT, LICENSE at repo root
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_RELEASE_DIST ON)       # -> 1.el9
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)         # -> xrd-ucache-<v>-1.el9.x86_64.rpm
set(CPACK_RPM_PACKAGE_DESCRIPTION
    "An XrdCl client plugin (libXrdClUCache.so) and CLI that cache the pages \
your jobs read from root:// URLs on local disk, so repeat passes over the \
same data are served locally. Fail-open by construction: any cache problem \
degrades to a normal uncached read. Activation is per-user and needs no \
administrator: run `ucache setup` once. Works with any XRootD 5.6+ client \
stack, including CMSSW and LCG/CVMFS ROOT builds.")

include(CPack)
